environmentType:
githubRepoName:
githubRepoOwner:
githubAccessTokenName:
projectType: ts # value should be either: ts or js
sslCertificateArn: # optional: add ssl certificate ARN if you want alb with ssl

dev:
  stackName:
  branch:
  pipelineBucket:
  pipelineConfig:
    name:
  minSize: 1
  maxSize: 1
  instanceTypes: t3.small
  ebEnvName:
  ebAppName:
<<<<<<< HEAD
  healthCheckPath: / # change if required
  envVariables: # add as many vars you want
=======
  envVariables: # optional: add as many vars as you want
>>>>>>> 6201adaac27d154f14ca0b4b100d4274fcb89062
    - name: name_a
      value: VALUE_A
    - name: name_b
      value: VALUE_B
